import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderNav } from "./ui/header-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} bg-gradient-to-br from-cws-bg-1 to-cws-bg-2`}
			>
				<HeaderNav />
				<main className="min-h-screen max-w-screen-2xl mx-auto">
					{children}
				</main>
			</body>
		</html>
	);
}
